services:
  prismcast:
    # 2026.02.02
    # GitHub home for this project with setup instructions: https://github.com/hjdhjd/prismcast.
    # Docker container home for this project: https://hub.docker.com/r/bnhf/prismcast.
    image: bnhf/prismcast:${TAG:-latest}
    container_name: prismcast
    hostname: prismcast
    dns_search: ${DOMAIN:-localdomain}
    shm_size: '1gb'
    ports:
      - ${HOST_PORT:-5589}:5589
      - ${HOST_VNC_PORT:-5900}:5900
      - ${HOST_NOVNC_PORT:-6080}:6080
      - ${HOST_HDHR_PORT:-5004}:5004
    environment:
      - DISPLAY_NUM=${DISPLAY_NUM:-99}
      - SCREEN_WIDTH=${SCREEN_WIDTH:-1920}
      - SCREEN_HEIGHT=${SCREEN_HEIGHT:-1080}
      - SCREEN_DEPTH=${SCREEN_DEPTH:-24}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5589/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - prismcast-data:/root/.prismcast
    restart: unless-stopped
volumes:
  prismcast-data:
